version: "3.8"

services:
  flask_template:
    build:
      context: .
    container_name: flask_template
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - SCRIPT_NAME=/flask_template
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask_template.rule=PathPrefix(`/flask_template`)"
      - "traefik.http.services.flask_template.loadbalancer.server.port=5000"
    networks:
      - traefik_default
    expose:
      - "5000"

networks:
  traefik_default:
    external: true
